server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: superbase-auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    azure:
      servicebus:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
        entity-name: ${AZURE_SERVICE_BUS_QUEUE_NAME}
        entity-type: queue

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
