#Dockerfile.dev
FROM mcr.microsoft.com/devcontainers/java:21

# Install Maven
ARG MAVEN_VERSION=3.9.6
RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | tar -xz -C /opt/
RUN ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/local/bin/mvn

# Install additional development tools
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    git \
    curl \
    vim \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# install the azure cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
# expose the port
EXPOSE 8080

# Set the default shell to bash
ENV SHELL /bin/bash